dist: bionic

language: python
python:
  - '3.8'
  - '3.7'
  - '3.6'
install:
  # Upstream defaults to world-read-writeable /dev/kvm. Debian/Ubuntu override
  # this; see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892945. We want
  # the upstream default.
  - sudo echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /lib/udev/rules.d/99-fix-kvm.rules > /dev/null
  - sudo udevadm control --reload-rules
  # On systemd >= 238 we can use udevadm trigger -w and remove udevadm settle.
  - sudo udevadm trigger /dev/kvm
  - sudo udevadm settle
script: python setup.py test -K

addons:
  apt:
    packages:
      - libbz2-dev
      - liblzma-dev
      - qemu-kvm
      - zlib1g-dev
      - zstd
